### ISSUE TITLE
ODHack: Document the AccountV3 Contract

### ISSUE THREAD

**Issue by Darlington02** [horuslabsio/tokenbound-contract-docs#2]
Description: 
This documentation will serve as a reference for developers and users who want to understand the AccountV3.

**Goals:**

- Explain the purpose of the AccountV3 contract.
- Document the available functions

**References:**

- Link to existing documentation: https://docs.tbaexplorer.com/starknet-tokenbound-sdk/introduction-to-tokenbound
- Link to the AccountV3 contract code: https://github.com/horuslabsio/TBA/blob/v3/src/accountV3/accountV3.cairo
- New to contract documentations? Check out this sample docs as a guide: https://contracts-v2-docs.lens.xyz/contracts/libraries/ProfileLib.sol/library.ProfileLib

**Comment by Iwueseiter** [comment]
Hi @Darlington02 can I work on this?
Here is a link to a comprehensive docs I've written and have been merged  https://github.com/Flex-NFT-Marketplace/Flex-Marketplace-Contract/pull/107

**Comment by ShantelPeters** [comment]
Hi @Darlington02 please I will like to work on this ?

**Comment by petersdt** [comment]
hi @Darlington02  can i work on this task if still open for contribution

**Comment by CollinsC1O** [comment]
Hello @Darlington02 I will love to work on this

**Comment by Iwueseiter** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/erc6551-token-bound-accounts-on-starknet).

### My background and how it can be leveraged
Hi @Darlington02 can I work on this?


### How I plan on tackling this issue
Here is a link to a comprehensive docs I've written and have been merged Flex-NFT-Marketplace/Flex-Marketplace-Contract#107
