### ISSUE TITLE
ODHack: Document the upgradeable component

### ISSUE THREAD

**Issue by Darlington02** [horuslabsio/tokenbound-contract-docs#4]
Description: 
This documentation will serve as a reference for developers and users who want to understand the functionality of the upgradeable component. 

**Goals:**

- Explain the purpose of the Upgradeable component.
- Document the available functions

**References:**

- Link to existing documentation: https://docs.tbaexplorer.com/starknet-tokenbound-sdk/introduction-to-tokenbound
- Link to the code: https://github.com/horuslabsio/TBA/blob/v3/src/components/upgradeable/upgradeable.cairo
- New to contract documentations? Check out this sample docs as a guide: https://contracts-v2-docs.lens.xyz/contracts/libraries/ProfileLib.sol/library.ProfileLib

**Comment by Jemiiah** [comment]
I

**Comment by CollinsC1O** [comment]
Hello @Darlington02 I will love to work on this

**Comment by NueloSE** [comment]
@Darlington02 can i be assigned to work on this . some of my previous merged documentation:

- [cairo quiz ](https://github.com/cairo-book/cairo-book/pull/779)
- [starknet.js](https://github.com/starknet-io/starknet.js/pull/1100)

**Comment by Naomi-Gift** [comment]
@Darlington02 Can I work on this ?
I am a web3 developer/ Technical writer
I have experience in a lot of open source contributions especially in making Documentation
Here are some of the merged docs I’ve written
https://github.com/Flex-NFT-Marketplace/Flex-Marketplace-Contract/commit/fc28412ba108a61919b75ed1d7ab2e140ce9fbd0
https://hackmd.io/@xZ4BOZ5TTTy1I0ZQHXFOkg/rkFBcGgAC

**Comment by Joy-Adah** [comment]
Hi @Darlington02 I would love to work on this. Can I be assigned?

**Comment by PoulavBhowmick03** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/erc6551-token-bound-accounts-on-starknet).

### My background and how it can be leveraged
I'm Poulav Bhowmick, a software engineer at Invisible Studios with a robust background in TypeScript, Rust, Solidity Cairo, fullstack development and blockchain technology. My experience includes building robust applications, optimizing functionalities and blockchain integration. I have actively participated in events and open source contributions, enhancing my capability to tackle real-world tech challenges. My projects can be viewed on my GitHub Profile and OnlyDust Profile. Plus I´m active member of Starknet, Ethereum exosystem.

### How I plan on tackling this issue
I will take a look at the current code and documentation and work on writing it as asked
ETA - 3 days

**Comment by raizo07** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/erc6551-token-bound-accounts-on-starknet).

### My background and how it can be leveraged
Hello @Darlington I'll like to be assigned to work on this. I'm a SOftware Dev with over four years experience and have worked on the Docss of several Projects on Starknet. 

Here is a link to my profile https://app.onlydust.com/u/raizo07

**Comment by Jemiiah** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/erc6551-token-bound-accounts-on-starknet).

### My background and how it can be leveraged
I have a great rack record in documentation issue

### How I plan on tackling this issue
Review the Existing Documentation:
Thoroughly understand the purpose and functionality of the upgradeable component as outlined in the existing documentation provided.
Study the Code:
Analyze the code in the upgradeable component (upgradeable.cairo) to gain insight into the implementation details and available functions.
Draft the New Documentation:
Begin by explaining the core purpose and benefits of using the upgradeable component.
Detail the various functions available within the component and their respective use cases.
Format and Structure:
Organize the documentation in a clear and structured format for easy comprehension by developers and users.
Utilize examples, code snippets, and diagrams where necessary to enhance understanding.
