### ISSUE TITLE
ODHack: Document the lockable component

### ISSUE THREAD

**Issue by Darlington02** [horuslabsio/tokenbound-contract-docs#5]
Description: 
This documentation will serve as a reference for developers and users who want to understand the functionality of the Lockable component. 

**Goals:**

- Explain the purpose of the Lockable component.
- Document the available functions.

**References:**

- Link to existing documentation: https://docs.tbaexplorer.com/starknet-tokenbound-sdk/introduction-to-tokenbound
- Link to the code: https://github.com/horuslabsio/TBA/blob/v3/src/components/lockable/lockable.cairo
- - New to contract documentations? Check out this sample docs as a guide: https://contracts-v2-docs.lens.xyz/contracts/libraries/ProfileLib.sol/library.ProfileLib

**Comment by ShantelPeters** [comment]
Please I will love to take this up @Darlington02

**Comment by CollinsC1O** [comment]
Hi @Darlington02 I will love to work on this

**Comment by Kaminar-i** [comment]
@Darlington02, I'd be happy to have this issue

**Comment by petersdt** [comment]
Hi @Darlington02, Kindly assign me this issue as i would be able to handle this task. ETA <72hrs. 
example of previous documentation merged: 
[cairo book quiz](https://github.com/cairo-book/cairo-book/pull/788)

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/erc6551-token-bound-accounts-on-starknet).

### My background and how it can be leveraged
Hi I would love to work on this issue

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/erc6551-token-bound-accounts-on-starknet).

### My background and how it can be leveraged
Hello @Darlington02 i will love to take up on this please

### How I plan on tackling this issue
I can implement the documentation for the lockable component

**Comment by Jemiiah** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/erc6551-token-bound-accounts-on-starknet).

### My background and how it can be leveraged
 I would love to work on this issue I have worked on about 6 different documentation issue on different repositories this is my OD Hack portfolio with over 50 contributions https://app.onlydust.com/u/Jemiiah I have a very good track record on docs issues here are some of the repositories I have worked on:
https://github.com/Flex-NFT-Marketplace/Flex-Marketplace-Contract/pull/106
https://github.com/dragan2234/worldcoin-scroll-bridge/pull/13
https://github.com/dragan2234/worldcoin-scroll-bridge/pull/11
https://github.com/NethermindEth/StarknetByExample/pull/200

### How I plan on tackling this issue
I would do the work correctly and accurately with ETA of at most 48 hrs
