### ISSUE TITLE
ODHack: Document the Permissionable component

### ISSUE THREAD

**Issue by Darlington02** [horuslabsio/tokenbound-contract-docs#6]
Description: 
This documentation will serve as a reference for developers and users who want to understand the functionality of the Permissionable component. 

**Goals:**

- Explain the purpose of the Permissionable component.
- Document the available functions.

**References:**

- Link to existing documentation: https://docs.tbaexplorer.com/starknet-tokenbound-sdk/introduction-to-tokenbound
- Link to the code: https://github.com/horuslabsio/TBA/blob/v3/src/components/permissionable/permissionable.cairo
- New to contract documentations? Check out this sample docs as a guide: https://contracts-v2-docs.lens.xyz/contracts/libraries/ProfileLib.sol/library.ProfileLib

**Comment by martinvibes** [comment]
hello @Darlington02 please i'm ready and i would love to take on this issue
i'm a `frontend developer` and a `technical writer`

here are some of the docs i have writting:
[https://github.com/cairo-book/cairo-book/blob/main/src/ch16-05-01-price-feeds.md](https://github.com/cairo-book/cairo-book/blob/main/src/ch16-05-01-price-feeds.md)
[https://github.com/bandada-infra/bandada/blob/main/README.md](https://github.com/bandada-infra/bandada/blob/main/README.md)
[https://github.com/lfglabs-dev/starknet.quest/blob/testnet/docs/CONTRIBUTING.md](https://github.com/lfglabs-dev/starknet.quest/blob/testnet/docs/CONTRIBUTING.md)

please assign me :)

**Comment by vestor-dev** [comment]
hello @Darlington02 i would love to work on this issue

**Comment by NueloSE** [comment]
hello @Darlington02  can i be assigned to work on this task

previous contributions:

- [cairo book](https://github.com/cairo-book/cairo-book/pull/982)
- [what happens when you press enter key](https://hackmd.io/@nuelo/whathappenswhen)
- [cairo smart contract](https://hackmd.io/@nuelo/rJroBcwzC)

**Comment by Naomi-Gift** [comment]
@Darlington02 Can I work on this ?
I am a web3 developer/ Technical writer
I have experience in a lot of open source contributions especially in making Documentation
Here are some of the merged docs I’ve written
https://github.com/Flex-NFT-Marketplace/Flex-Marketplace-Contract/commit/fc28412ba108a61919b75ed1d7ab2e140ce9fbd0
https://hackmd.io/@xZ4BOZ5TTTy1I0ZQHXFOkg/rkFBcGgAC

**Comment by Naomi-Gift** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/erc6551-token-bound-accounts-on-starknet).

### My background and how it can be leveraged

I am a web3 developer/ Technical writer
 

### How I plan on tackling this issue
I have experience in a lot of open source contributions especially in making Documentation
Here are some of the merged docs I’ve written
Flex-NFT-Marketplace/Flex-Marketplace-Contract@fc28412
https://hackmd.io/@xZ4BOZ5TTTy1I0ZQHXFOkg/rkFBcGgAC

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/erc6551-token-bound-accounts-on-starknet).

### My background and how it can be leveraged
hello i am a frontend developer and a technical writer 
please can i work on this issue :)
i would love to be a contributor on this repo



### How I plan on tackling this issue
Purpose: Clarify the role of the Permissionable component.
Functions: Document the key functions available in the component.
References: Use the provided links for guidance on style and structure.

**Comment by 0xdevcollins** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/erc6551-token-bound-accounts-on-starknet).

### My background and how it can be leveraged
My name is Collins Ikechukwu. I'm a full stack blockchain developer developer and a technical writer 

### How I plan on tackling this issue
I can work on this task

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/erc6551-token-bound-accounts-on-starknet).

### My background and how it can be leveraged
Hello @Darlington02 i will love to work on this please

### How I plan on tackling this issue
I can implement the documentation for the permissionable component
